server:
  port: 8085

spring:
  application:
    name: ai-chat-service
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.150.11:3306/tianji_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.150.11:8848
      config:
        server-addr: 192.168.150.11:8848
        import-check:
          enabled: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

deepseek:
  api-url: https://api.deepseek.com/v1/chat/completions
  model: deepseek-chat

spring:
  ai:
    openai:
      api-key: ${SILICONFLOW_API_KEY:sk-sbkcnrewdutwpkewypfxuesnkkspblvfznnuqioruchpslcd}
      base-url: https://api.siliconflow.cn/v1
      embedding:
        options:
          model: BAAI/bge-large-zh-v1.5

# Milvus 向量数据库连接
milvus:
  host: 192.168.150.11
  port: 19530
  collection-name: product_vectors
