server:
  port: 8083

spring:
  application:
    name: pay-service
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.150.11:3306/tianji_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.150.11:8848
      config:
        server-addr: 192.168.150.11:8848
        import-check:
          enabled: false
    sentinel:
      transport:
        dashboard: 192.168.150.11:8858
      eager: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# ==================== Knife4j API 文档 ====================
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
knife4j:
  enable: true
  setting:
    language: zh_cn

alipay:
  gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  notify-url: https://t8e56477.natappfree.cc/api/pay/notify
